# Build and run tests every night on non-Docker systems.
name: ARM64 Image

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    paths: 
      - ".github/workflows/docker-arm64-build.yml"
      - ".github/workflows/docker-image-test.yml"
#  schedule:
#    - cron:  '45 2 * * *'

jobs:
  arm64_build:
    name: Build
    runs-on: buildjet-4vcpu-ubuntu-2204-arm

    steps:
      - name: Checkout repository      
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: terminusdb/terminusdb-server:local
          outputs: type=docker,dest=terminusdb-server-snapshot-arm64.tar
          platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            TERMINUSDB_GIT_HASH=${{ github.sha }}

      - name: Compress image
        run: gzip terminusdb-server-snapshot-arm64.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
            name: terminusdb-server-snapshot-arm64
            path: terminusdb-server-snapshot-arm64.tar.gz

  arm64_tests:
    name: Tests
    needs: arm64_build
    uses: ./.github/workflows/docker-image-test.yml
    with:
      test_repository: ${{ github.repository }}
      test_ref: ${{ github.sha }}
      image_artifact: terminusdb-server-snapshot-arm64
      image_platform: linux/arm64
      runner: buildjet-4vcpu-ubuntu-2204-arm
      mocha_parallel: false
